# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: coil-qc-code

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

launch_buttons:
  notebook_interface: "jupyterlab"

# Information about where the book exists on the web
repository:
  url: https://github.com/mathieuboudreau/coil-qc-code  # Online location of your book
  branch: main   # Which branch of the repository should be used when creating links (optional)

only_build_toc_files: true

execute:
  timeout: 36000


config:
    nb_execution_mode: off