name: Clear Notebook Outputs on Commit

on:
  push:
    branches:
      - main

jobs:
  strip-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install nbstripout
        run: |
          pip install nbstripout
          nbstripout --install

      - name: Clear Notebook Outputs
        run: |
          nbstripout --force --keep-count .
