name: Run Notebooks and Save Outputs

on:
  push:
    branches:
      - main  # Trigger the action on the main branch

jobs:
  run-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clear GitHub Action Caches
        run: |
          echo "Clearing caches..."
          sudo rm -rf ~/.cache/pip
          sudo rm -rf executed_notebooks

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Jupyter Notebooks
        run: |
          mkdir -p executed_notebooks
          for notebook in $(find . -name "*.ipynb"); do
            echo "Executing $notebook"
            jupyter nbconvert --to notebook --execute --inplace \
              --output executed_notebooks/$(basename $notebook) $notebook \
              2>&1 | tee -a notebook_execution.log || exit 1
          done

      - name: Copy Executed Notebooks to Pages Directory
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          mkdir -p gh-pages/$COMMIT_SHA
          cp executed_notebooks/*.ipynb gh-pages/$COMMIT_SHA/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages
