name: Run Notebooks and Save Outputs

on:
  push:
    branches:
      - main  # Trigger the action on the main branch

jobs:
  run-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clear GitHub Action Caches
        run: |
          echo "Clearing caches..."
          sudo rm -rf ~/.cache/pip
          sudo rm -rf executed_notebooks

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install papermill

      - name: Verify Installation and PATH
        run: |
          pip list
          echo $PATH
          which openneuro-py

      - name: Run Jupyter Notebooks
        run: |
          mkdir -p executed_notebooks
          # for notebook in $(find . -name "*.ipynb"); do
          #   echo "Executing $notebook"
          #   papermill $notebook executed_notebooks/$(basename $notebook) \
          #     2>&1 | tee -a notebook_execution.log || exit 1
          # done
          # TODO: once #42 is fixed, re-introduce the human notebook
          papermill data_processing-phantom.ipynb executed_notebooks/$(basename data_processing-phantom.ipynb) 2>&1 | tee -a notebook_execution.log || exit 1

      - name: Commit and Push Notebooks with Outputs
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git checkout -b with-outputs || git checkout with-outputs
          cp -r executed_notebooks/* .
          git add *.ipynb
          git commit -m "Add notebooks with outputs"
          git push --force origin with-outputs
